[general]
  name = "Léon Hollender"
[email]
  userzoom = "lhollender@userzoom.com"
  personal = "hello@leonh.fr"
[github]
  userzoom = "lhollender-uz"
  personal = "leonhfr"
[macos]
  computer_name = "lhollender-macbook"
[borgbackup]
  include = [
    "calibre-kobo",
    "calibre-tablet",
    "Official",
    "Pictures"
  ]
  exclude = [
    "go",
    "leonhfr",
    "Library",
    "oss",
    "uz"
  ]
