[".antigen"]
  type = "git-repo"
  url = "https://github.com/zsh-users/antigen.git"
  refreshPeriod = "168h"

[".config/cheat/cheatsheets/community"]
  type = "git-repo"
  url = "https://github.com/cheat/cheatsheets"
  refreshPeriod = "168h"
