worktree-path = "{{ repo_path }}/../{{ repo }}.{{ branch | sanitize }}" # https://worktrunk.dev/config/#worktree-path-template

[commit.generation]
command = "MAX_THINKING_TOKENS=0 claude -p --no-session-persistence --model=haiku --tools='' --safe-mode --setting-sources='user' --system-prompt=''"

[list]
summary = false
full = false
branches = false
remotes = false
json-schema = 2
timeout-ms = 0

[merge]
squash = true
commit = true
rebase = true
remove = true
verify = true
ff = true

[remove]
delete-branch = true

[switch]
cd = true

[switch.picker]
pager = "delta --features='line-numbers decorations'"

[projects."github.com/qonto-private/*"]
forge.platform = "github"
forge.hostname = "github-work"

[pre-start]
copy-claude-settings = """
mkdir -p {{ worktree_path }}/.claude \
  && cp {{ base_worktree_path }}/.claude/settings.local.json {{ worktree_path }}/.claude/settings.local.json 2>/dev/null \
  || true
"""
